FROM python:3.8

WORKDIR ./revolutModel

COPY requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt

COPY ./revolutModel ./revolutModel

EXPOSE 5000

CMD ["python", "revolutModel/your_python_script.py"]
